version: '3.5'
services:
    app:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - ${DIR}:/application:cached
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    web:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ${DIR}:/application:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    db:
        image: postgres:9.6-alpine
        working_dir: /application
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=app
volumes:
    database:
    appdata:
